### ISSUE TITLE
New quicklisp libraries are not added to quickdocs

### ISSUE THREAD

**Issue by mrossini-ethz** [quickdocs/quickdocs-updater#2]
Hi

Two of my libraries ([parseq](https://github.com/mrossini-ethz/parseq) and [physical-quantities](https://github.com/mrossini-ethz/physical-quantities)) were added to quicklisp last month (01.07.2017). [Meanwhile there was a new update to quicklisp (25.07.2017).] They don't seem to be added to quickdocs. This is true also for other new libraries.

Admittedly, it has not been a full month since 01.07.2017, but it says the following on the quickdocs page:

> Always up-to-date
All documentation is generated automatically, moments after the monthly Quicklisp updates.

Would you mind having a look at this issue?

Thank you.

**Comment by fukamachi** [comment]
Hi, sorry for the delay and they’re indexes now.
Closing.

**Comment by mrossini-ethz** [comment]
Great, thanks!
